require("units/beings/rail/RailVehicle")
require("units/beings/rail/RailWheeledVehicle")
require("units/beings/rail/Rail2WheeledVehicle")
require("units/beings/rail/Pickup/RailPickup")
require("units/beings/rail/Pickup/RailPickupDamage")
require("units/beings/rail/HunterKiller/HunterKillerDamage")
require("units/beings/rail/HunterKiller/HunterKillerDamageData")
require("units/beings/rail/RailDamage")
require("units/beings/rail/TurretDamage")
require("units/beings/player/PlayerRail")
require("units/weapons/BikerGatling")
require("units/weapons/SkynetDefenceTurretGatling")
require("units/weapons/M2MachineGun")
require("units/weapons/Mk19GrenadeLauncher")
require("units/beings/rail/Pickup/RailPickupTargetingInfo")
require("units/weapons/PipeBombDamage")
require("units/beings/rail/DriveTest/RailDriveTestBase")
require("units/beings/rail/DriveTest/RailDriveTestInput")
require("units/beings/rail/DriveTest/RailDriveTestControl")
require("units/beings/rail/DriveTest/RailDriveTestUnitCamera")
require("units/beings/rail/DriveTest/RailDriveTestControllerInterpreter")
require("units/beings/rail/driver/Driver")
require("units/beings/rail/Passenger/Passenger")
require("units/beings/rail/cameras/DynamicLinkCamera")
require("units/SequenceUnitDamage.lua")
require("units/beings/rail/HunterKiller/RailHunterKiller")
require("units/beings/rail/RailPath")
require("units/beings/rail/biker/Biker")
require("units/beings/rail/biker/BikerDamage")
require("units/beings/rail/walker_driver/WalkerDriver")
require("units/beings/rail/Van/RailVehicleVan")
require("units/beings/rail/Van/RailVehicleVanDamage")
require("units/beings/rail/Train/RailTrain")
require("units/beings/rail/Train/RailTrainDamage")
require("units/beings/rail/SchoolBus/RailSchoolBus")
require("units/beings/rail/SchoolBus/RailSchoolBusDamage")
require("units/beings/rail/Tank/RailTankDamage")
require("units/beings/rail/Tank/RailTank")
require("units/beings/player_tank/PlayerTankControllerInterpreter")
require("units/beings/player_tank/PlayerTankInput")
require("units/beings/player_tank/control/PlayerTankControl")
require("units/beings/player_tank/PlayerTank")
require("units/beings/player_tank/PlayerTankCamera")
require("units/beings/rail/Buggy/RailBuggy")
require("units/beings/rail/Buggy/RailBuggyDamage")
require("units/beings/rail/Pickup/RailDodgeRamDamage")
base_require("units/weapons/PipeBomb", nil, "RELEASE")
base_require("units/data/VehicleData", nil, "RELEASE")
RailSetup = RailSetup or class()
function RailSetup.init()
	local L0_0, L1_1
end
function RailSetup.update(A0_2, A1_3)
end
