base_require("units/beings/player/PlayerDamage", nil, "RELEASE")
base_require("units/beings/player/PlayerTargetingInfo", nil, "RELEASE")
base_require("units/beings/player/PlayerCamera", nil, "RELEASE")
base_require("units/beings/player/Player", nil, "RELEASE")
base_require("units/beings/player/PlayerPickupTarget", nil, "RELEASE")
base_require("units/beings/player/LocalPlayer", nil, "RELEASE")
base_require("units/beings/player/Aim", nil, "RELEASE")
base_require("units/beings/player/PlayerSensoryEvents", nil, "RELEASE")
base_require("units/beings/player/PlayerInventory", nil, "RELEASE")
base_require("units/beings/player/PlayerVisibilityQuery", nil, "RELEASE")
base_require("units/beings/player/PlayerDifficultyLevel", nil, "RELEASE")
require("units/beings/player/PlayerAiNerveSystem")
require("units/beings/CharacterInput")
require("units/beings/player/control/PlayerControl")
require("units/beings/CharacterControllerInterpreter/CppControllerInterpreters")
require("units/beings/player/cameras/FollowCamera")
require("units/beings/player/cameras/AimSwitchCamera")
require("units/beings/player/cameras/CoverSideCamera")
require("units/beings/player/cameras/CoverHeightCamera")
require("units/beings/player/cameras/AimCamera")
require("units/beings/player/cameras/PlayerAimCamera")
require("units/beings/player/cameras/DocumentaryCamera")
require("units/beings/player/cameras/TargetingCamera")
require("units/beings/player/cameras/EnvironmentCamera")
require("units/beings/player/cameras/CoverEdgeOffsetCamera")
require("units/beings/player/look/PlayerLook")
require("units/beings/player/mission_objective/PlayerMissionObjective")
require("units/beings/player/PlayerCameraControllerInterpreter")
require("units/beings/player/PlayerPhysics")
require("units/beings/player/sounds/PlayerSound")
require("units/beings/player/PlayerPickupOutline")
require("units/beings/player/PlayerEnemyWeakspotOutline")
require("units/beings/player/PlayerTeammateOutline")
