core:register_core_module("core/utils/CoreApp")
core:register_core_module("core/utils/CoreClass")
core:register_core_module("core/utils/CoreCode")
core:register_core_module("core/utils/CoreDebug")
core:register_core_module("core/utils/CoreEvent")
core:register_core_module("core/utils/CoreEws")
core:register_core_module("core/utils/CoreInput")
core:register_core_module("core/utils/CoreKeywordArguments")
core:register_core_module("core/utils/CoreMath")
core:register_core_module("core/utils/CoreOldModule")
core:register_core_module("core/utils/CoreString")
core:register_core_module("core/utils/CoreTable")
core:register_core_module("core/utils/CoreUnit")
core:register_core_module("core/utils/CoreXml")
core:register_core_module("core/utils/dev/ews/color_picker/CoreColorPickerDialog", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/ews/color_picker/CoreColorPickerPanel", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/ews/color_picker/CoreColorPickerDraggables", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/ews/color_picker/CoreColorPickerFields", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreClipsBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreMusicEditor2", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreMusicMonitor", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreSongProject", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreMarkerEditBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreMarkersBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreModeCrossfadeBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreModeTimingBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreModesBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreSmartListCtrl", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreSongCrossfadeBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/music_editor/CoreStartStopBox", core.PRODUCTION_ONLY)
core:register_core_module("core/managers/music/CoreMusicManager")
core:register_core_module("core/managers/music/CoreMusicPlayer")
core:register_core_module("core/managers/music/CoreSong")
core:register_core_module("core/managers/music/CoreSongExporter")
core:register_core_module("core/managers/music/CoreModePlayHead")
core:register_core_module("core/managers/music/CoreSoundPlayHead")
core:register_core_module("core/managers/music/CoreMusicTimeControl")
core:register_core_module("core/managers/subtitle/CoreSubtitleManager")
core:register_core_module("core/managers/subtitle/CoreSubtitlePresenter")
core:register_core_module("core/managers/subtitle/CoreSubtitleSequence")
core:register_core_module("core/managers/subtitle/CoreSubtitleSequencePlayer")
core:register_core_module("core/utils/dev/tools/luaprofiler_viewer/CoreLuaProfilerViewer", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/luaprofiler_viewer/CoreLuaProfilerTreeBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/tools/luaprofiler_viewer/CoreLuaProfilerGridBox", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/CoreDependencyParser", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/CoreDependencyNode", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreGameDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreLevelDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreUnitDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreObjectDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreMaterialconfigDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreMaterialDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreTextureDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreCutsceneDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/dependencymapper/dependencynodes/CoreEffectDn", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/spreadsheat/CoreSpreadsheet", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/spreadsheat/CoreWorkbook", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/spreadsheat/CoreWorksheet", core.PRODUCTION_ONLY)
core:register_core_module("core/utils/dev/spreadsheat/CoreSsRow", core.PRODUCTION_ONLY)
core:register_core_module("core/managers/CoreLocalizationManager")
core:register_core_module("core/managers/CoreNewsReportManager")
core:register_core_module("core/managers/CoreSettingsManager")
core:register_core_module("core/managers/CoreShadowManager")
core:register_core_module("core/managers/viewport/CoreScriptViewport")
core:register_core_module("core/managers/viewport/CoreViewportManagerVPInterface")
core:register_core_module("core/managers/viewport/CoreViewportManager2")
core:register_core_module("core/managers/viewport/CoreScriptViewportVMInterface")
core:register_core_module("core/managers/environment/CoreEnvironmentManager2")
core:register_core_module("core/managers/environment/CoreEnvironmentManagerVPMInterface")
core:register_core_module("core/managers/environment/CoreLightEnvironment")
core:register_core_module("core/managers/environment/CoreSky")
core:register_core_module("core/managers/environment/CoreUnderlayEffect")
core:register_core_module("core/managers/environment/CorePostEffect")

