require("ai/machines/walker/WalkerAiBehavior")
require("ai/machines/walker/WalkerAiMovement")
require("ai/machines/walker/WalkerAiCombat")
require("ai/machines/walker/WalkerAiData")
WalkerAiSetup = WalkerAiSetup or class()
function WalkerAiSetup.init(A0_0)
	managers.aihivebrain:register_logicfunctions(WalkerAiBehavior)
	managers.aihivebrain:register_logicfunctions(WalkerAiMovement)
	managers.aihivebrain:register_logicfunctions(WalkerAiCombat)
end
